#!/usr/bin/env bash
# Allows us to connect to my server using the private key with user ubuntu
ssh -i ~/.ssh/school ubuntu@54.237.9.194
ssh -i ~/alx-system_engineering-devops/0x0B-ssh/school2 ssh ubuntu@54.237.9.194
